# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/qwqawawow/nix-index-database/releases/download/2025-04-27-033009/index-";
  hashes = {
    x86_64-linux = "sha256-lGr94uX73/F4JaLyDEBCP49qwJyQPAh61biNRy3xVz4=";
    aarch64-linux = "sha256-FuIGhMwL8oszQJkkcjm4oV2akvCkDQyoUM9/TCPt8o4=";
    x86_64-darwin = "sha256-O2sqD6Jac6xj9aAutJVlW43YGjEQFJeu3NgBWipyBIQ=";
    aarch64-darwin = "sha256-2Tv24RO9LEsObNf4keZCDp8WyXxDA9gQDxjfKFR2vX8=";
  };
}
