# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/eihqnh/nix-index-database/releases/download/2026-03-29-050219/index-";
  hashes = {
    x86_64-linux = "sha256-j9wwvyq3RMHk9Nmieh/oNafYAjKOzm7ZJh7hOH6EqkI=";
    aarch64-linux = "sha256-vbOhQzwbp3KJCymK/fAobgtrL5a/g1Xt5jxtNh0EVaw=";
    x86_64-darwin = "sha256-5K+AQkr6Hd5Er18lpuIy2KOc7wSQcE6/21c42FjaUOM=";
    aarch64-darwin = "sha256-JRIoUVpvSkyNt9pVrehmtUGTC8s2LI2WDUeK3/FTmKU=";
  };
}
