# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/eihqnh/nix-index-database/releases/download/2025-12-28-040159/index-";
  hashes = {
    x86_64-linux = "sha256-zZVT7JhjbU7nJej1pMwwgr6UDKSrcpu2NwzVCz+lXAY=";
    aarch64-linux = "sha256-2MufyskeWDx0Ccg8w6ynjiGGAW6rHEBKgCfbikOmXKA=";
    x86_64-darwin = "sha256-oC3yyhEb7ys1jJF6ncoTnqs1zsUhaPPIh/cjzE5ATXQ=";
    aarch64-darwin = "sha256-Fy7qbLNnZBlaHiF/fkSpB50S2bSIlchj7KdvOZw3TJM=";
  };
}
