# this file is autogenerated by .github/workflows/update.yml
{
  x86_64-linux.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-06-09-030603/index-x86_64-linux";
    sha256 = "19nm1x3fd164ddwk64yq1m7jam4fvh65l30cjvzd1j6196rw067j";
  };
  aarch64-linux.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-06-09-030603/index-aarch64-linux";
    sha256 = "0fq081w1ap5ajy3jz63bac22w9wi5pm16lh6kmr3pnww2za50c7j";
  };
  x86_64-darwin.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-06-09-030603/index-x86_64-darwin";
    sha256 = "11irpvj4z1dj0wd52vyzc5x1c4a1hrrv31rynvc73q463rdmf6sa";
   };
  aarch64-darwin.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-06-09-030603/index-aarch64-darwin";
    sha256 = "16vf7x6ldvvy8ydiw2b5h0j7zmmj9bfqp3955z1s7q286c226ixd";
  };
}
