# this file is autogenerated by .github/workflows/update.yml
{
  x86_64-linux.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-07-14-030921/index-x86_64-linux";
    sha256 = "0aq5g8m346df1vbq8lmvdls9dl8zhk7my5j61kf17i1nfsj2isg3";
  };
  aarch64-linux.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-07-14-030921/index-aarch64-linux";
    sha256 = "12xjfgzx8zmrvjk02zf2fwpnarsr9mhl9q8x9pi8snr2c2j598mf";
  };
  x86_64-darwin.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-07-14-030921/index-x86_64-darwin";
    sha256 = "17iixr557dypwslqyznns13vbd48izc3rlhi4yqw6wd50yny0iwy";
   };
  aarch64-darwin.database = builtins.fetchurl {
    url = "https://github.com/qwqawawow/nix-index-database/releases/download/2024-07-14-030921/index-aarch64-darwin";
    sha256 = "05ac3gizjgaxk3f87zzl3plyxk6jbv4x6kr2rf60jr6aiaps8l7v";
  };
}
